server:
  port: 9900
  servlet:
    session:
      cookie:
        secure: false
        http-only: false
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  session:
    timeout: 30m
#    store-type: redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  druid:
    # 配置可视化控制台页面
    stat-view-servlet:
      enabled: false
      # 访问德鲁伊监控页面的地址
      url-pattern: /druid/*
  data:
    redis:
      host: 192.168.31.90
      port: 9400
      database: 0
      password: xiaotree
      # 连接超时
      connect-timeout: 5s
      # 读超时
      timeout: 5s
      # Lettuce 客户端的配置
      lettuce:
        # 连接池配置
        pool:
          # 最小空闲连接
          min-idle: 1
          # 最大空闲连接
          max-idle: 8
          # 最大活跃连接
          max-active: 8
          # 从连接池获取连接 最大超时时间，小于等于0则表示不会超时
          max-wait: 5000ms
  cache:
#    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterAccess=3600s
    redis:
      # 以毫秒为单位
      time-to-live: 1800000

  mvc:
    static-path-pattern: /resources/**
  web:
    resources:
      # 本地静态资源地址
      static-locations:
        - file:///D:/Software/web/
      cache:
        cachecontrol:
          cache-private: true
          max-age: 604800
file:
  upload: D:/Software/web/upload/

mybatis-flex:
  datasource:
    mysql:
      name: jinyu
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.31.90:3306/jinyu?serverTimezone=Asia/Shanghai
      username: xiaotree
      password: 234234*Qw
      filters: stat
  mapper-locations:
    - classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org:
      springframework:
        security: TRACE
#        beans: DEBUG
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss